### ISSUE TITLE
RuntimeError: cuDNN error

### ISSUE THREAD

**Issue by Troye-van** [Equationliu/Attack-ImageNet#2]
When I run your code, I get this error:

**RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.**

The error occurs when I run line 83 "loss.backward()" in **attacker.py**, I don't know what's going on here.
Maybe you know how to solve it?

**Comment by Equationliu** [comment]
> When I run your code, I get this error:
> 
> **RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.**
> 
> The error occurs when I run line 83 "loss.backward()" in **attacker.py**, I don't know what's going on here.
> Maybe you know how to solve it?

we have no python file named attacker.py. maybe [here](https://github.com/pytorch/pytorch/issues/32564) can help you.

**Comment by Troye-van** [comment]
Ok, thanks a lot!
