### ISSUE TITLE
关于Multi-Scale Attack的技巧有没有放入源码的问题

### ISSUE THREAD

**Issue by Suelence-hu** [Equationliu/Attack-ImageNet#3]
您好，请问一下，这个源码加入了Multi-Scale Attack的技巧了吗，为什么我使用此源码去长期赛提交结果得分是1.7多，如果要达到是3点多是不是还是要再编辑源码呢

**Comment by Equationliu** [comment]
> 您好，请问一下，这个源码加入了Multi-Scale Attack的技巧了吗，为什么我使用此源码去长期赛提交结果得分是1.7多，如果要达到是3点多是不是还是要再编辑源码呢

The multi-scale trick is [here](https://github.com/Equationliu/Attack-ImageNet/blob/c3ef6226947f5112f91aa328a39bc1704d471ff5/main.py#L62).  Maybe you can ref to [blog](https://tianchi.aliyun.com/forum/postDetail?spm=5176.12586969.1002.12.3a673d88RgM2wn&postId=87278) for more details.

**Comment by Suelence-hu** [comment]
> > 您好，请问一下，这个源码加入了Multi-Scale Attack的技巧了吗，为什么我使用此源码去长期赛提交结果得分是1.7多，如果要达到是3点多是不是还是要再编辑源码呢
> 
> The multi-scale trick is [here](https://github.com/Equationliu/Attack-ImageNet/blob/c3ef6226947f5112f91aa328a39bc1704d471ff5/main.py#L62). Maybe you can ref to [blog](https://tianchi.aliyun.com/forum/postDetail?spm=5176.12586969.1002.12.3a673d88RgM2wn&postId=87278) for more details.

好的，非常感谢，我再仔细检查下代码，可能是我改动了某些东西导致分数不高，我再重新生成一下
